# specify the version of readthedocs
version: 2

build:
   apt_packages:
    - python3-dev
    - gdal-bin
    - python3-gdal
    - python-gdal
    - libgdal-dev
    - g++
    
# Build documentation in the docs/ directory with Sphinx
sphinx:
   builder: html
   configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.7
   install:
      - requirements:
           - docs_requirements_setuptools.txt
           - docs_requirements.txt
      - method: pip
        path: .
        extra_requirements:
           - tests
           - docs
